# Define the system of units to use internally. 
InternalUnitSystem:
  UnitMass_in_cgs:     1.98841e43    # 10^10 M_sun
  UnitLength_in_cgs:   3.08567758e24 # 1 Mpc
  UnitVelocity_in_cgs: 1e5           # 1 km/s
  UnitCurrent_in_cgs:  1             # Amperes
  UnitTemp_in_cgs:     1             # Kelvin

Cosmology:
  Omega_cdm:      0.30
  Omega_lambda:   0.70
  Omega_b:        0.0
  h:              0.70
  a_begin:        0.04
  a_end:          1

# Parameters governing the time integration
TimeIntegration:
  dt_min:     1e-6
  dt_max:     1e-2

# Parameters for the self-gravity scheme
Gravity:
  eta:          0.025
  MAC:          adaptive
  theta_cr:     0.7
  epsilon_fmm:  0.001
  comoving_DM_softening: 0.0625
  max_physical_DM_softening: 0.0625
  mesh_side_length:       64

# Parameters governing the snapshots
Snapshots:
  basename:            ./outputs/SWIFT/snap
  delta_time:          1.01
  scale_factor_first:  0.10 # z = 9
  compression:         4
  invoke_fof:          1

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          1.01
  scale_factor_first:  0.1

Scheduler:
  max_top_level_cells: 8
  cell_split_size:     50

# Parameters related to the initial conditions
InitialConditions:
  file_name:                   ./outputs/monofonic/ics_swift.hdf5
  periodic:                    1
  cleanup_h_factors:           0
  cleanup_velocity_factors:    0
 
# Parameters of the Friends-Of-Friends module
FOF:
   basename:                        ./outputs/SWIFT/fof_output # Filename for the FOF outputs.
   min_group_size:                  32 # Minimum number of particles required for a group.
   linking_types:                   [0, 1, 0, 0, 0, 0, 0]  # Which particle types to consider for linking    (here only DM)
   attaching_types:                 [1, 0, 0, 0, 1, 1, 0]  # Which particle types to consider for attaching  (here gas, stars, and BHs)
   linking_length_ratio:            0.2         # Linking length in units of the main inter-particle separation.
   seed_black_holes_enabled:        0           # Do not seed black holes when running FOF
 
